### ISSUE TITLE
The proyect is not working

### ISSUE THREAD

**Issue by soportedontec** [techformist/simple-vue-html-axios-demo#2]
When i run it on the browser, anythings happens. I have test it with vue development but there's no problems. Thanks!
Awsome work!!!

**Comment by prashanth1k** [comment]
Thanks for catching that - that was me being incredibly stupid. 

`mode: "history"` will not function when directly opening the html page. We could either -

- use a simple server to serve the directory e.g. `http-server` ([link](https://www.npmjs.com/package/http-server))
- change `mode: "hash"` to make the project work when the index.html is opened in browser (there may be additional changes required for linking stuff, but am trying to keep things simple)

I have updated the [article](https://techformist.com/use-vue-from-url-simple-app/) to reflect this as well.
